# Generated by Django 4.1.4 on 2023-01-16 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Operative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_po', models.CharField(max_length=11)),
                ('production_entry_date', models.CharField(max_length=8)),
                ('manufacturing_date', models.CharField(max_length=8)),
                ('item', models.IntegerField()),
                ('used_raw_material', models.CharField(max_length=11)),
                ('unloading_raw_material', models.FloatField()),
                ('used_finished_product', models.CharField(max_length=11)),
                ('unloading_finished_product', models.FloatField()),
                ('observations', models.CharField(max_length=1500)),
                ('firm', models.CharField(max_length=5)),
            ],
        ),
    ]
