# Generated by Django 4.1.4 on 2023-01-17 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operative', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='operative',
            options={'verbose_name': 'Operario', 'verbose_name_plural': 'Operarios'},
        ),
    ]
