# Generated by Django 4.1.4 on 2023-01-23 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operative', '0004_alter_operative_manufacturing_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operative',
            name='firm',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='operative',
            name='manufacturing_date',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='operative',
            name='observations',
            field=models.CharField(max_length=1500),
        ),
        migrations.AlterField(
            model_name='operative',
            name='production_entry_date',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='operative',
            name='used_finished_product',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='operative',
            name='used_raw_material',
            field=models.CharField(max_length=11),
        ),
    ]
