# Generated by Django 4.1.4 on 2023-01-25 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operative', '0006_alter_operative_production_entry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operative',
            name='production_entry_date',
            field=models.CharField(max_length=8, verbose_name='Ingraso a produccion dd/mm/aa'),
        ),
    ]
