# Generated by Django 4.1.4 on 2023-01-25 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operative', '0007_alter_operative_production_entry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operative',
            name='firm',
            field=models.CharField(max_length=5, verbose_name='Firma'),
        ),
        migrations.AlterField(
            model_name='operative',
            name='manufacturing_date',
            field=models.CharField(max_length=8, verbose_name='Fecha macanizado (dd/mm/aa)'),
        ),
        migrations.AlterField(
            model_name='operative',
            name='observations',
            field=models.CharField(max_length=1500, verbose_name='Observaciones'),
        ),
        migrations.AlterField(
            model_name='operative',
            name='production_entry_date',
            field=models.CharField(max_length=8, verbose_name='Ingraso a produccion (dd/mm/aa)'),
        ),
        migrations.AlterField(
            model_name='operative',
            name='used_finished_product',
            field=models.CharField(max_length=11, verbose_name='Prducto terminado utilizado'),
        ),
        migrations.AlterField(
            model_name='operative',
            name='used_raw_material',
            field=models.CharField(max_length=11, verbose_name='Material utilizado'),
        ),
    ]
