# Generated by Django 4.1.4 on 2023-01-28 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operative', '0010_rename_unloading_finished_product_operative_mp_mm_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operative',
            name='used_finished_product',
            field=models.CharField(max_length=11, verbose_name='Producto terminado utilizado'),
        ),
    ]
