# Generated by Django 4.1.4 on 2023-01-16 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Planner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_po', models.CharField(max_length=11)),
                ('admission_date', models.CharField(max_length=8)),
                ('client', models.CharField(max_length=30)),
                ('coh', models.CharField(max_length=10)),
                ('doh', models.CharField(max_length=10)),
                ('date_required', models.CharField(max_length=8)),
                ('dispatch', models.BooleanField(default=True)),
                ('item', models.IntegerField()),
                ('raw_material', models.CharField(max_length=11)),
                ('raw_material1', models.BooleanField(default=True)),
                ('finished_product', models.CharField(max_length=15)),
                ('finished_product1', models.BooleanField(default=True)),
            ],
        ),
    ]
