# Generated by Django 4.1.4 on 2023-01-16 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='planner',
            name='firm',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
