# Generated by Django 4.1.4 on 2023-01-16 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0002_planner_firm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planner',
            name='firm',
        ),
    ]
