# Generated by Django 4.1.4 on 2023-01-17 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0003_remove_planner_firm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planner',
            name='admission_date',
            field=models.DateField(),
        ),
    ]
