# Generated by Django 4.1.4 on 2023-01-17 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0004_alter_planner_admission_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planner',
            name='admission_date',
            field=models.CharField(max_length=8),
        ),
    ]
