# Generated by Django 4.1.4 on 2023-01-17 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0005_alter_planner_admission_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='planner',
            options={'verbose_name': 'Planificador', 'verbose_name_plural': 'Planificadores'},
        ),
    ]
