# Generated by Django 4.1.4 on 2023-01-19 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0006_alter_planner_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planner',
            name='dispatch',
            field=models.CharField(choices=[('consolidated', 'consolidado'), ('bus', 'micro'), ('withdraw', 'retira')], max_length=25),
        ),
    ]
