# Generated by Django 4.1.4 on 2023-01-23 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0010_alter_planner_dispatch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planner',
            name='n_po',
            field=models.CharField(max_length=11, verbose_name='N°OP'),
        ),
    ]
