# Generated by Django 4.1.4 on 2023-01-23 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0011_alter_planner_n_po'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planner',
            name='admission_date',
            field=models.CharField(max_length=8, verbose_name='Fecha de ingreso'),
        ),
        migrations.AlterField(
            model_name='planner',
            name='client',
            field=models.CharField(max_length=30, verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='planner',
            name='date_required',
            field=models.CharField(max_length=8, verbose_name='Fecha de requerida'),
        ),
        migrations.AlterField(
            model_name='planner',
            name='dispatch',
            field=models.CharField(choices=[('consolidated', 'consolidado'), ('bus', 'micro'), ('withdraw', 'retira')], default='consolidated', max_length=12),
        ),
        migrations.AlterField(
            model_name='planner',
            name='finished_product',
            field=models.CharField(max_length=15, verbose_name='Producto Terminado'),
        ),
        migrations.AlterField(
            model_name='planner',
            name='finished_product1',
            field=models.BooleanField(default=True, verbose_name='PT en Stock'),
        ),
        migrations.AlterField(
            model_name='planner',
            name='raw_material',
            field=models.CharField(max_length=11, verbose_name='Materia Prima'),
        ),
        migrations.AlterField(
            model_name='planner',
            name='raw_material1',
            field=models.BooleanField(default=True, verbose_name='MP en Stock'),
        ),
    ]
