# Generated by Django 4.1.4 on 2023-01-25 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0012_alter_planner_admission_date_alter_planner_client_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planner',
            name='dispatch',
            field=models.CharField(choices=[('consolidated', 'consolidado'), ('bus', 'micro'), ('withdraw', 'retira')], default='consolidatedo', max_length=12),
        ),
    ]
