# Generated by Django 4.1.4 on 2023-01-25 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0013_alter_planner_dispatch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planner',
            name='dispatch',
            field=models.CharField(choices=[('consolidated', 'consolidado'), ('bus', 'micro'), ('withdraw', 'retira')], default='consolidated', max_length=12),
        ),
    ]
