# Generated by Django 4.1.4 on 2023-01-25 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0014_alter_planner_dispatch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planner',
            name='admission_date',
            field=models.CharField(max_length=8, verbose_name='Fecha de ingreso(dd/mm/aa)'),
        ),
        migrations.AlterField(
            model_name='planner',
            name='date_required',
            field=models.CharField(max_length=8, verbose_name='Fecha de requerida(dd/mm/aa)'),
        ),
    ]
