# Generated by Django 4.1.4 on 2023-01-16 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Logistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_po', models.CharField(max_length=11)),
                ('dispatch_date', models.CharField(max_length=8)),
                ('coh', models.CharField(max_length=10)),
                ('doh', models.CharField(max_length=10)),
                ('client', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=30)),
                ('dispatch', models.BooleanField(default=True)),
                ('form_of_dispatch', models.CharField(max_length=30)),
                ('item', models.IntegerField()),
                ('raw_material', models.CharField(max_length=11)),
                ('raw_material1', models.BooleanField(default=True)),
                ('finished_product', models.CharField(max_length=15)),
                ('finished_product1', models.BooleanField(default=True)),
                ('observations', models.CharField(max_length=1500)),
                ('firm', models.CharField(max_length=5)),
            ],
        ),
    ]
