# Generated by Django 4.1.4 on 2023-01-16 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='logistics',
            old_name='raw_material',
            new_name='used_raw_material',
        ),
        migrations.RenameField(
            model_name='logistics',
            old_name='raw_material1',
            new_name='used_raw_material1',
        ),
    ]
