# Generated by Django 4.1.4 on 2023-01-16 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0002_rename_raw_material_logistics_used_raw_material_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='logistics',
            old_name='finished_product',
            new_name='used_finished_product',
        ),
        migrations.RenameField(
            model_name='logistics',
            old_name='finished_product1',
            new_name='used_finished_product1',
        ),
    ]
