# Generated by Django 4.1.4 on 2023-01-23 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0005_alter_logistics_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logistics',
            name='n_po',
            field=models.CharField(max_length=11, verbose_name='N°OP'),
        ),
    ]
