# Generated by Django 4.1.4 on 2023-01-25 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0007_alter_logistics_form_of_dispatch_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logistics',
            name='form_of_dispatch',
            field=models.CharField(choices=[('consolidated', 'consolidado'), ('bus', 'micro'), ('withdraw', 'retira')], default='consolidado', max_length=12),
        ),
    ]
