# Generated by Django 4.1.4 on 2023-01-25 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0010_alter_logistics_form_of_dispatch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logistics',
            name='n_po',
            field=models.CharField(max_length=11, verbose_name='N°OP'),
        ),
    ]
