# Generated by Django 4.1.4 on 2023-01-25 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0011_alter_logistics_n_po'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logistics',
            name='address',
            field=models.CharField(max_length=30, verbose_name='Direccion'),
        ),
        migrations.AlterField(
            model_name='logistics',
            name='client',
            field=models.CharField(max_length=30, verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='logistics',
            name='dispatch',
            field=models.BooleanField(default=True, verbose_name='Despachado'),
        ),
        migrations.AlterField(
            model_name='logistics',
            name='form_of_dispatch',
            field=models.CharField(choices=[('consolidated', 'consolidado'), ('bus', 'micro'), ('withdraw', 'retira')], max_length=12, verbose_name='Forma de despacho'),
        ),
    ]
