# Generated by Django 4.1.4 on 2023-01-25 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0013_alter_logistics_firm_alter_logistics_observations_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logistics',
            name='dispatch_date',
            field=models.CharField(max_length=8, verbose_name='Ingraso a produccion (dd/mm/aa)'),
        ),
    ]
