# Generated by Django 4.1.4 on 2023-01-26 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0014_alter_logistics_dispatch_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logistics',
            name='dispatch_date',
            field=models.CharField(max_length=8, verbose_name='Ingreso a produccion (dd/mm/aa)'),
        ),
    ]
