# Generated by Django 4.1.4 on 2023-01-27 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0016_alter_logistics_dispatch_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logistics',
            name='form_of_dispatch',
            field=models.CharField(choices=[('consolidado', 'consolidado'), ('micro', 'micro'), ('retira', 'retira')], max_length=12, verbose_name='Forma de despacho'),
        ),
    ]
